"""add entra id fields

Revision ID: 96daf2bcba2e
Revises: 406c99a49057
Create Date: 2025-05-11 22:13:38.936913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96daf2bcba2e'
down_revision = '406c99a49057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_entra_user', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('entra_user_id', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_user_entra_user_id', ['entra_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_entra_user_id', type_='unique')
        batch_op.drop_column('entra_user_id')
        batch_op.drop_column('is_entra_user')

    # ### end Alembic commands ###
